/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/daisyui/dist/**/*.js',
  ],
  safelist: [
    // ボタン関連
    'btn',
    'btn-primary',
    'btn-secondary',
    'btn-accent',
    'btn-lg',
    'btn-md',
    'btn-sm',
    'btn-outline',
    // レイアウト関連
    'hero',
    'hero-content',
    'hero-overlay',
    'card',
    'card-body',
    'card-title',
    'card-actions',
    'modal',
    'modal-box',
    'modal-backdrop',
    'navbar',
    'navbar-start',
    'navbar-center',
    'navbar-end',
    'drawer',
    'drawer-toggle',
    'drawer-content',
    'drawer-side',
    // 背景色
    'bg-base-100',
    'bg-base-200',
    'bg-base-300',
    'bg-primary',
    'bg-secondary',
    'bg-accent',
    'bg-neutral',
    'bg-info',
    'bg-success',
    'bg-warning',
    'bg-error',
    // テキスト色
    'text-base-content',
    'text-primary',
    'text-primary-content',
    'text-secondary',
    'text-secondary-content',
    'text-accent',
    'text-accent-content',
    'text-neutral',
    'text-neutral-content',
    'text-info',
    'text-info-content',
    'text-success',
    'text-success-content',
    'text-warning',
    'text-warning-content',
    'text-error',
    'text-error-content',
    // その他のDaisyUIクラス
    'divider',
    'badge',
    'alert',
    'progress',
    'loading',
    'tooltip',
    'collapse',
    'carousel',
    'tabs',
    'tab',
    'steps',
    'step',
    // 状態クラス
    'hover:bg-primary',
    'hover:text-primary-content',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-primary',
    // アニメーション
    'transition-all',
    'duration-300',
    'ease-in-out',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
      },
      fontFamily: {
        'raleway': ['Raleway', 'sans-serif'],
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      "nord",
      {
        nord: {
          "primary": "oklch(59.435% 0.077 254.027)",
          "primary-content": "oklch(11.887% 0.015 254.027)",
          "secondary": "oklch(69.651% 0.059 248.687)",
          "secondary-content": "oklch(13.93% 0.011 248.687)",
          "accent": "oklch(77.464% 0.062 217.469)",
          "accent-content": "oklch(15.492% 0.012 217.469)",
          "neutral": "oklch(45.229% 0.035 264.131)",
          "neutral-content": "oklch(89.925% 0.016 262.749)",
          "base-100": "oklch(95.127% 0.007 260.731)",
          "base-200": "oklch(93.299% 0.01 261.788)",
          "base-300": "oklch(89.925% 0.016 262.749)",
          "base-content": "oklch(32.437% 0.022 264.182)",
          "info": "oklch(69.207% 0.062 332.664)",
          "info-content": "oklch(13.841% 0.012 332.664)",
          "success": "oklch(76.827% 0.074 131.063)",
          "success-content": "oklch(15.365% 0.014 131.063)",
          "warning": "oklch(85.486% 0.089 84.093)",
          "warning-content": "oklch(17.097% 0.017 84.093)",
          "error": "oklch(60.61% 0.12 15.341)",
          "error-content": "oklch(12.122% 0.024 15.341)",
        },
      }
    ],
    darkTheme: false,
    base: true,
    styled: true,
    utils: true,
  },
}